### ISSUE TITLE
Fileupload with non ascii filename does not work

### ISSUE THREAD

**Issue by Jank1310** [Jank1310/datadolphin#86]
```
datadolphin-app-1       | TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["x-amz-meta-filename"]
datadolphin-app-1       |     at ClientRequest.setHeader (node:_http_outgoing:651:3)
datadolphin-app-1       |     at new ClientRequest (node:_http_client:291:14)
datadolphin-app-1       |     at Module.request (node:http:100:10)
datadolphin-app-1       |     at /app/nextjs/dist/server/app/api/upload/route.js:1:34623
datadolphin-app-1       |     at new Promise (<anonymous>)
datadolphin-app-1       |     at iu (/app/nextjs/dist/server/app/api/upload/route.js:1:34595)
datadolphin-app-1       |     at iW.makeRequestStreamAsync (/app/nextjs/dist/server/app/api/upload/route.js:5:2534)
datadolphin-app-1       |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
datadolphin-app-1       |   code: 'ERR_INVALID_CHAR'
datadolphin-app-1       | }
datadolphin-app-1       |  ⨯ Error: Error uploading file
datadolphin-app-1       |     at iQ (/app/nextjs/dist/server/app/api/upload/route.js:5:56889)
datadolphin-app-1       |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
datadolphin-app-1       |     at async iY (/app/nextjs/dist/server/app/api/upload/route.js:5:56365)
datadolphin-app-1       |     at async /app/nextjs/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:42484
datadolphin-app-1       |     at async eI.execute (/app/nextjs/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:32486)
datadolphin-app-1       |     at async eI.handle (/app/nextjs/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:43737)
datadolphin-app-1       |     at async doRender (/app/nextjs/node_modules/next/dist/server/base-server.js:1333:42)
datadolphin-app-1       |     at async cacheEntry.responseCache.get.routeKind (/app/nextjs/node_modules/next/dist/server/base-server.js:1555:28)
datadolphin-app-1       |     at async NextNodeServer.renderToResponseWithComponentsImpl (/app/nextjs/node_modules/next/dist/server/base-server.js:1463:28)
datadolphin-app-1       |     at async NextNodeServer.renderPageComponent (/app/nextjs/node_modules/next/dist/server/base-server.js:1856:24)
````

**Comment by Jank1310** [comment]
Uploaded fix
